version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: madhesh23
    DOCKERHUB_PASSWORD: Maddy@9180

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Build phase skipped (using prebuilt image madhesh23/my-custom-nginx:1.0)
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'

